sources:
  aws:
    # Take the aws default profile in ~/.aws/credentials and collect 2 regions
    region: ["us-east-1", "eu-central-1"]

  k8s:
    # Use the default kubeconfig file and collect all contexts.
    config_files:
      - path: "~/.kube/config"
        all_contexts: true
destinations:
  sqlite:
    database: resoto.db