name: 🐛 Bug Report
description: Report a problem
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the bug or issue.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Resoto are you running?
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description:
    validations:
      required: false
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: Please tell us how we can reproduce the undesired behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. (This will be automatically formatted into code, so no need for backticks.)
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional information or screenshots that may be relevant or helpful.
  - type: markdown
    attributes:
      value: |
        By submitting this bug report, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).
