name: Check PR cloud2sql
on:
  push:
    tags:
      - "*.*.*"
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  cloud2sql:
    name: "cloud2sql"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Restore dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip-${{hashFiles('**/requirements*.txt')}}
          restore-keys: |
            ${{runner.os}}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox wheel flake8 build

      - name: Run tests
        run: tox

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/

      - name: Publish distribution to PyPI
        if: github.ref_type == 'tag'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_CLOUD2SQL }}
          packages_dir: ./dist/

      - name: Build binary
        id: pyinstaller
        run: |
          pip install pyinstaller
          pyinstaller --clean --noconfirm --log-level=WARN --distpath=dist --workpath=build cloud2sql.spec
          if [ "${{ github.ref_type }}" = tag ]; then
              echo "target=cloud2sql-${{ github.ref_name }}.linux-amd64" >> $GITHUB_OUTPUT
          else
              echo "target=cloud2sql-${GITHUB_SHA::7}.linux-amd64" >> $GITHUB_OUTPUT
          fi

      - name: Move binary
        run: |
          mv dist/cloud2sql dist/${{ steps.pyinstaller.outputs.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.pyinstaller.outputs.target }}
          path: dist/${{ steps.pyinstaller.outputs.target }}
